### ISSUE TITLE
(move-dup-mode nil) should disable the mode

### ISSUE THREAD

**Issue by alphapapa** [wyuenho/move-dup#6]
I use the global mode, but in some modes I want to disable it (like in org-mode, where it messes up the subtree-moving binds).  I tried putting both `(move-dup-mode)` and `(move-dup-mode nil)` in my org mode-hook, but neither one disables the minor mode.

I don't know a lot about elisp or making modes, but from what I can tell, `move-dup-mode` doesn't accept `nil` to disable it.  It would be really helpful if it did, like several other minor modes do.  :)

Thanks.

**Comment by wyuenho** [comment]
I don't much elisp either :) 

All I did was used the default minor mode macro and globalized macro, which will automatically create a variable called `global-move-dup-mode`. You can set it to `nil` in your org-mode hook I think.

**Comment by alphapapa** [comment]
Ah, wow, I had forgotten about this.  :)

I happened to discover recently that those macros use `-1` instead of nil.  So `(move-dup-mode -1)` works.  Must be one of those anachronistic things that sticks around, because `nil` and `t` seem to make sense.

Thanks.
